import datetime

EPOCH: datetime.datetime = datetime.datetime(1970, 1, 1, tzinfo=datetime.timezone.utc)

_HTTP_CODE = int

# HTTP Status Codes
HTTP_OK: _HTTP_CODE = 200
HTTP_CREATED: _HTTP_CODE = 201
HTTP_NO_CONTENT: _HTTP_CODE = 204
HTTP_PARTIAL_CONTENT: _HTTP_CODE = 206
HTTP_RESUME_INCOMPLETE: _HTTP_CODE = 308
HTTP_BAD_REQUEST: _HTTP_CODE = 400
HTTP_UNAUTHORIZED: _HTTP_CODE = 401
HTTP_NOT_FOUND: _HTTP_CODE = 404
HTTP_CONFLICT: _HTTP_CODE = 409
HTTP_RANGE_NOT_SATISFIABLE: _HTTP_CODE = 416
HTTP_ERROR: _HTTP_CODE = 500
HTTP_NOT_IMPLEMENTED: _HTTP_CODE = 501
